name: Running tests
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:
jobs:
  test:
    name: Test - PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - (${{ matrix.dependency-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8, 8.1]
        laravel: [^8.0, ^9.0]
        dependency-version: [prefer-stable, prefer-lowest]
        exclude:
          - php: 8.1
            laravel: ^8.0
    timeout-minutes: 15
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, zip
          coverage: none
      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist --no-suggest
      - name: Run tests
        run: composer test